ALTER TABLE bible_book ENABLE ROW LEVEL SECURITY;

ALTER TABLE bible_chapter ENABLE ROW LEVEL SECURITY;

ALTER TABLE bible_verse ENABLE ROW LEVEL SECURITY;

ALTER TABLE bible_version ENABLE ROW LEVEL SECURITY;